### PR TITLE
pt_BR translation

### PR DESCRIPTION
**Pull request by ricardogarim**
Hi!
For testing purposes of the system I had to translate for Brazilian Portuguese.
It's a little contribution now but I hope that in the future I'll be capable to make more PR's.

### CODE REVIEW

**Comment by moeiscool** [comment]
How did you make the file? Using the translator tool or manually? Either way, thank you very much!

**Comment by ricardogarim** [comment]
Mostly manually, and some cases with translator help. Some expressions may don't be right cause I'm really don't know them.
I will be making changes as soon as possible.

**Comment by moeiscool** [comment]
Well even if some aren't exact it is better than not having any translation :) Your efforts are grand already, thank you.

**Comment by ricardogarim** [comment]
Thanks! And sorry for the mistakes when commiting the changes (those three commits that should be just one).

**Comment by moeiscool** [comment]
haha no worries! github just logs the changes for us to see. The very last commit is what is put up for review :)

**Pull request merged**
