### PR TITLE
Add RTMP input stream support

### PR DESCRIPTION
**Pull request by vmirage**
Allow RTMP as the input source.

### CODE REVIEW

**Comment by moeiscool** [comment]
do you have a short tutorial or example URL i can try to use the RTMP method? i just wanna see a stream in  Shinobi and be able to give a method if asked for one :)

Thank you!

**Comment by vmirage** [comment]
You can try a test RTMP stream from here

https://www.hdwplayer.com/rtmp-player/

RTMP url:
rtmp://184.72.239.149/vod/BigBuckBunny_115k.mov

For me, I use ffmpeg to convert RTSP stream to RTMP to stream over the internet since RTSP won't work behind router due to the random UDP port being open for the stream. I use red5 server as the RTMP server.

Conversion
ffmpeg -i rtsp://192.168.1.200/11 -c:v copy -c:a copy -f flv rtmp://localhost/live/stream1

Playback url
rtmp://(server address)/live/stream1

**Comment by centurion800** [comment]
hi, How i can  mix audio from another source?

**Comment by moeiscool** [comment]
i manually made the changes because other things needed to be changed as well for this to work properly

**Pull request closed without merging**
